/**
 * The tables whose records carry provenance (created_by/updated_by,
 * created_at/updated_at; migration 0115), i.e. the objects a page may show
 * it for. Kept in step with the migration by lib/provenance/tables.test.ts.
 */
export const PROVENANCE_TABLES = [
  "tenant_memberships",
  "user_roles",
  "roles",
  "groups",
  "group_members",
  "group_roles",
  "authorization_policies",
  "sso_connections",
  "tenant_settings",
  "tenant_domains",
  "agent_api_keys",
  "feature_flags",
  "agents",
  "agent_identities",
  "agent_contracts",
  "agent_owners",
  "agent_relationships",
  "agent_duplicate_candidates",
  "identities",
  "identity_relationships",
  "identity_lifecycle_tasks",
  "identity_attribute_definitions",
  "identity_source_links",
  "integrations",
  "integration_credentials",
  "identity_sources",
  "pending_identity_correlations",
  "connector_receivers",
  "onboarding_proposals",
  "application_discoveries",
  "applications",
  "accounts",
  "entitlements",
  "access_grants",
  "access_requests",
  "access_request_approvals",
  "access_request_policies",
  "access_packages",
  "access_package_resources",
  "access_package_assignments",
  "access_package_assignment_items",
  "data_sources",
  "policies",
  "application_onboardings",
  "runtime_tools",
  "runtime_resources",
  "runtime_emergency_controls",
  "risk_findings",
  "investigations",
  "investigation_findings",
  "risk_severity_weights",
  "certification_campaigns",
  "certification_items",
  "control_mappings",
  "governance_attestations",
  "privacy_requests",
  "privacy_breach_incidents",
  "privacy_consent_purposes",
  "privacy_processing_activities",
  "privacy_retention_policies",
  "privacy_legal_holds",
  "privacy_settings",
  "reports",
  "notification_preferences",
  "billing_profiles",
] as const;

export type ProvenanceTable = (typeof PROVENANCE_TABLES)[number];
